version: '3.8'

services:
  main-server:
    build:
      context: ./main
    image: main-server-image
    container_name: main-server-container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server

  stats-server:
    build:
      context: ./stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm-stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ewm-stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
